--- #YAML:1.0
name:                TkUtil-Configure
version:             0.03
abstract:            Trap and act on Tk <Configure> events
license:             perl
author:              
    - X Cramps <cramps.the@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Perl6::Attributes:             0.04
    Test::More:                    0
    Time::HiRes:                   1.9711
    Tk:                            804.025
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
